//
//  DeveloperPreview.swift
//  Airbnb
//
//  Created by EDSON SANTOS on 31/05/2024.
//

import Foundation

class DeveloperPreview {
    
    static let shared = DeveloperPreview()
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Joe Doestring",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 3,
            numberOfBathrooms: 4,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerMight: 48,
            latitude: 38.736946,
            longitude: -9.142685,
            imageUrls: ["listing-1", "listing-2", "listing-3"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon Apartment",
            rating: 4.88,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .office, .laundry, .wifi, .tv],
            type: .apartment),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Mayk Doestring",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 2,
            pricePerMight: 52,
            latitude: 41.15,
            longitude: -8.61024,
            imageUrls: ["listing-11", "listing-12", "listing-13"],
            address: "123 Main Ave",
            city: "Porto",
            state: "Porto",
            title: "Porto GrandHouse",
            rating: 4.78,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .pool, .wifi, .tv, .laundry, .alarmSystem],
            type: .house),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Joseph Agamenon",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerMight: 28,
            latitude: 41.15,
            longitude: -8.61024,
            imageUrls: ["listing-14", "listing-12", "listing-13", "listing-11"],
            address: "123 Main Ave",
            city: "Porto",
            state: "Porto",
            title: "Porto TinyHouse",
            rating: 4.5,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .wifi, .tv, .alarmSystem],
            type: .tinyHouse),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Filipa Gulpa",
            ownerImageUrl: "profile-photo1",
            numberOfBedrooms: 4,
            numberOfBathrooms: 4,
            numberOfGuests: 8,
            numberOfBeds: 6,
            pricePerMight: 248,
            latitude: 38.736946,
            longitude: -9.142685,
            imageUrls: ["listing-10", "listing-3", "listing-9", "listing-7"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon Village",
            rating: 4.2,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .wifi, .tv, .pool, .alarmSystem],
            type: .villa),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Carla Muniz",
            ownerImageUrl: "profile-photo2",
            numberOfBedrooms: 4,
            numberOfBathrooms: 4,
            numberOfGuests: 8,
            numberOfBeds: 6,
            pricePerMight: 148,
            latitude: 38.736946,
            longitude: -9.142685,
            imageUrls: ["listing-9", "listing-6", "listing-7", "listing-10"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon MyVillage",
            rating: 4.65,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .wifi, .tv, .office, .pool, .balcony,  .alarmSystem],
            type: .villa),
    ]
}
