//
//  DeveloperPreview.swift
//  Airbnb
//
//  Created by EDSON SANTOS on 31/05/2024.
//

import Foundation

class DeveloperPreview {
    
    var listings: [Listing] = [
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Joe Doestring",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 3,
            numberOfBathrooms: 4,
            numberOfGuests: 4,
            numberOfBeds: 4,
            pricePerMight: 48,
            latitude: 25.7522,
            longitude: -88.1935,
            imageUrls: ["listing-1", "listing-2", "listing-3"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon Apartment",
            rating: 4.88,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .office, .laundry, .wifi, .tv],
            type: .apartment),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Mayk Doestring",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 2,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 2,
            pricePerMight: 52,
            latitude: 25.622,
            longitude: -80.0335,
            imageUrls: ["listing-4", "listing-5", "listing-6"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon GrandHouse",
            rating: 4.78,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .pool, .wifi, .tv, .laundry, .alarmSystem],
            type: .house),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Joseph Agamenon",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 1,
            numberOfBathrooms: 1,
            numberOfGuests: 2,
            numberOfBeds: 1,
            pricePerMight: 28,
            latitude: 25.4522,
            longitude: -80.2935,
            imageUrls: ["listing-7", "listing-8", "listing-1", "listing-4"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon TinyHouse",
            rating: 4.88,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .wifi, .tv, .alarmSystem],
            type: .tinyHouse),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Augustus Gulp",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 4,
            numberOfGuests: 8,
            numberOfBeds: 6,
            pricePerMight: 248,
            latitude: 25.4522,
            longitude: -80.2935,
            imageUrls: ["listing-5", "listing-3", "listing-1", "listing-8"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon Village",
            rating: 4.88,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .wifi, .tv, .pool, .alarmSystem],
            type: .villa),
        .init(
            id: NSUUID().uuidString,
            ownerUId: NSUUID().uuidString,
            ownerName: "Carlos Martin",
            ownerImageUrl: "profile-photo",
            numberOfBedrooms: 4,
            numberOfBathrooms: 4,
            numberOfGuests: 8,
            numberOfBeds: 6,
            pricePerMight: 148,
            latitude: 25.4522,
            longitude: -80.2935,
            imageUrls: ["listing-2", "listing-1", "listing-7", "listing-4"],
            address: "123 Main Ave",
            city: "Lisbon",
            state: "Lisbon",
            title: "Lisbon MyVillage",
            rating: 4.88,
            features: [.selfCheckIn, .superHost],
            amenities: [.kitchen, .wifi, .tv, .office, .pool, .balcony,  .alarmSystem],
            type: .villa),
    ]
}
